modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_source}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "assets/roughlyenoughinputmethods/logo.png"

[[dependencies.${mod_id}]]
modId = "roughlyenoughitems"
mandatory = true
versionRange = "${forge_rei_range}"
ordering = "AFTER"
side = "CLIENT"